### ISSUE TITLE
Can't make kang

### ISSUE THREAD

**Issue by Encryptize** [friendly-telegram/friendly-telegram#38]
When I want to make a kang of stickers, I see this error.

`ERROR:root:Command failed
Traceback (most recent call last):
  File "/root/friendly-telegram/friendly-telegram/main.py", line 116, in handle_command
    await coro
  File "https://raw.githubusercontent.com/friendly-telegram/modules-repo/master/stickers.py", line 207, in kangcmd
    m1 = await conv.send_file(thumb, force_document=True)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/custom/conversation.py", line 89, in send_file
    self._input_chat, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/uploads.py", line 351, in send_file
    msg = self._get_response_message(request, await self(request), entity)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EMPTY (caused by SendMediaRequest)
ERROR:telethon.client.updates:Unhandled exception on functools.partial(<function handle_command at 0x7ffa644fda60>, <friendly-telegram.loader.Modules object at 0x7ffa611bcdd8>, <friendly-telegram.database.frontend.Database object at 0x7ffa611a8208>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 422, in _dispatch_update
    await callback(event)
  File "/root/friendly-telegram/friendly-telegram/main.py", line 124, in handle_command
    raise e
  File "/root/friendly-telegram/friendly-telegram/main.py", line 116, in handle_command
    await coro
  File "https://raw.githubusercontent.com/friendly-telegram/modules-repo/master/stickers.py", line 207, in kangcmd
    m1 = await conv.send_file(thumb, force_document=True)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/custom/conversation.py", line 89, in send_file
    self._input_chat, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/uploads.py", line 351, in send_file
    msg = self._get_response_message(request, await self(request), entity)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EMPTY (caused by SendMediaRequest)
ERROR:root:Command failed
Traceback (most recent call last):
  File "/root/friendly-telegram/friendly-telegram/main.py", line 116, in handle_command
    await coro
  File "https://raw.githubusercontent.com/friendly-telegram/modules-repo/master/stickers.py", line 207, in kangcmd
    m1 = await conv.send_file(thumb, force_document=True)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/custom/conversation.py", line 89, in send_file
    self._input_chat, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/uploads.py", line 351, in send_file
    msg = self._get_response_message(request, await self(request), entity)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EMPTY (caused by SendMediaRequest)
ERROR:telethon.client.updates:Unhandled exception on functools.partial(<function handle_command at 0x7ffa644fda60>, <friendly-telegram.loader.Modules object at 0x7ffa611bcdd8>, <friendly-telegram.database.frontend.Database object at 0x7ffa611a8208>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 422, in _dispatch_update
    await callback(event)
  File "/root/friendly-telegram/friendly-telegram/main.py", line 124, in handle_command
    raise e
  File "/root/friendly-telegram/friendly-telegram/main.py", line 116, in handle_command
    await coro
  File "https://raw.githubusercontent.com/friendly-telegram/modules-repo/master/stickers.py", line 207, in kangcmd
    m1 = await conv.send_file(thumb, force_document=True)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/custom/conversation.py", line 89, in send_file
    self._input_chat, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/uploads.py", line 351, in send_file
    msg = self._get_response_message(request, await self(request), entity)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EMPTY (caused by SendMediaRequest)
ERROR:root:Command failed
Traceback (most recent call last):
  File "/root/friendly-telegram/friendly-telegram/main.py", line 116, in handle_command
    await coro
  File "https://raw.githubusercontent.com/friendly-telegram/modules-repo/master/stickers.py", line 207, in kangcmd
    m1 = await conv.send_file(thumb, force_document=True)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/custom/conversation.py", line 89, in send_file
    self._input_chat, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/uploads.py", line 351, in send_file
    msg = self._get_response_message(request, await self(request), entity)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EMPTY (caused by SendMediaRequest)
ERROR:telethon.client.updates:Unhandled exception on functools.partial(<function handle_command at 0x7ffa644fda60>, <friendly-telegram.loader.Modules object at 0x7ffa611bcdd8>, <friendly-telegram.database.frontend.Database object at 0x7ffa611a8208>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 422, in _dispatch_update
    await callback(event)
  File "/root/friendly-telegram/friendly-telegram/main.py", line 124, in handle_command
    raise e
  File "/root/friendly-telegram/friendly-telegram/main.py", line 116, in handle_command
    await coro
  File "https://raw.githubusercontent.com/friendly-telegram/modules-repo/master/stickers.py", line 207, in kangcmd
    m1 = await conv.send_file(thumb, force_document=True)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/custom/conversation.py", line 89, in send_file
    self._input_chat, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/uploads.py", line 351, in send_file
    msg = self._get_response_message(request, await self(request), entity)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EMPTY (caused by SendMediaRequest)`

**Comment by penn5** [comment]
It fixed must update
