### ISSUE TITLE
.ban command

### ISSUE THREAD

**Issue by Whit3diamond** [friendly-telegram/friendly-telegram#60]
I tried to ban some one but this error appeared

ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Command failed
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 129, in handle_command
    await coro
  File "<string>", line 238, in ban
  File "/app/friendly-telegram/compat/util.py", line 123, in __getattr__
    return getattr(self.__under, name)
AttributeError: 'NoneType' object has no attribute 'delete'
ERROR:telethon.client.updates:Unhandled exception on functools.partial(<function handle_command at 0x7ff460e6e680>, <friendly-telegram.loader.Modules object at 0x7ff456adb750>, <friendly-telegram.database.frontend.Database object at 0x7ff456b75990>)
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/telethon/client/updates.py", line 422, in _dispatch_update
    await callback(event)
  File "/app/friendly-telegram/main.py", line 137, in handle_command
    raise e
  File "/app/friendly-telegram/main.py", line 129, in handle_command
    await coro
  File "<string>", line 238, in ban
  File "/app/friendly-telegram/compat/util.py", line 123, in __getattr__
    return getattr(self.__under, name)
AttributeError: 'NoneType' object has no attribute 'delete'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'
ERROR:root:Error running watcher
Traceback (most recent call last):
  File "/app/friendly-telegram/main.py", line 151, in handle_incoming
    await fun(message)
  File "/app/friendly-telegram/compat/raphielgang.py", line 315, in watcher
    await watcher(message)
  File "<string>", line 408, in muter
ModuleNotFoundError: No module named 'modules'

**Comment by penn5** [comment]
Unofficial external modules are not supported here.
